[package]
name = "imgui-glium-renderer"
version = "0.0.16-pre"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>", "imgui-rs contributors"]
description = "Glium renderer for the imgui crate"
homepage = "https://github.com/Gekkio/imgui-rs"
repository = "https://github.com/Gekkio/imgui-rs"
license = "MIT/Apache-2.0"
categories = ["gui", "rendering"]

[badges]
travis-ci = { repository = "Gekkio/imgui-rs" }

[dependencies]
glium = { git = "https://github.com/bogdad/glium", default-features = false, features = ["glutin"] }
imgui = { version = "0.0.16-pre", path = "../" }
imgui-sys = { version = "0.0.16-pre", path = "../imgui-sys", features = ["glium"] }
